spring:
  application:
    name: e-library-gateway-service
  security:
    user:
      name: user
      password: user

# gateway 8080, registry 8761, config 8081, data 8082, search 8083
server:
  port: 8080

zuul:
  #  ignored-services: '*'
  prefix: /api
  routes:
    e-library-data-service: /e-library-data-service/**

eureka:
  client:
    region: default
    serviceUrl:
      defaultZone: http://user:user@localhost:8761/eureka
    register-with-eureka: true
    fetch-registry: true
  instance:
    #    leaseRenewalIntervalInSeconds: 1
    #    leaseExpirationDurationInSeconds: 2
    prefer-ip-address: true

  #Setting logging levels
logging:
  level:
    com.hkd: DEBUG