#eureka-server-url: http://user:user@localhost:8761/eureka
eureka-server-url: http://user:user@e-library-registry-service:8761/eureka
#------------------------------------

spring:
  application:
    name: e-library-registry-service
  security:
    user: user
    password: user

# gateway 8080, registry 8761, config 8081, data 8082, search 8083
server:
  port: 8761

eureka:
  server:
    max-threads-for-peer-replication: 0
    enableSelfPreservation: false
    wait-time-in-ms-when-sync-empty: 0
  client:
    register-with-eureka: false
    fetchRegistry: false
  environment: hkd-local

service-url:
  defaultZone: ${eureka-server-url}

logging:
  level:
    com.netflix.eureka.registry: INFO
    org.springframework: INFO
    com.hkd: DEBUG