#mongo-url: mongodb://10.100.101.228:27017/e-library
mongo-url: mongodb://e-library-mongodb:27017/e-library

#eureka-server-url: http://user:user@localhost:8761/eureka
eureka-server-url: http://user:user@e-library-registry-service:8761/eureka
#------------------------------------

spring:
  data:
    mongodb:
      uri: ${mongo-url}

eureka:
  client:
    region: default
    service-url:
      defaultZone: ${eureka-server-url}
    register-with-eureka: true
    fetch-registry: true
    healthcheck:
      enabled: true
  instance:
    leaseRenewalIntervalInSeconds: 60
    leaseExpirationDurationInSeconds: 120
    prefer-ip-address: true

management:
  endpoints:
    web:
      exposure:
        include: '*'

logging:
  level:
    com.hkd: DEBUG

message: Hello HKD from Github application.yml