#eureka-server-url: http://user:user@localhost:8761/eureka
eureka-server-url: http://user:user@e-library-registry-service:8761/eureka
#---------------------------

spring:
  application:
    name: e-library-gateway-service
  security:
    user:
      name: user
      password: user

# gateway 8080, registry 8761, config 8081, data 8082, search 8083
server:
  port: 8080

zuul:
  #  ignored-services: '*'
  prefix: /api
  routes:
    e-library-data-service: /e-library-data-service/**

eureka:
  client:
    region: default
    service-url:
      defaultZone: ${eureka-server-url}
    register-with-eureka: true
    fetch-registry: true
    healthcheck:
      enabled: true
  instance:
    leaseRenewalIntervalInSeconds: 60
    leaseExpirationDurationInSeconds: 120
    prefer-ip-address: true

  #Setting logging levels
logging:
  level:
    com.hkd: DEBUG