spring:
  data:
    mongodb:
      uri: mongodb://bpm-tpg-228:27017/e-library

eureka:
  client:
    region: default
    serviceUrl:
      defaultZone: http://user:user@localhost:8761/eureka
    register-with-eureka: true
    fetch-registry: true
    healthcheck:
      enabled: true
  instance:
    leaseRenewalIntervalInSeconds: 60
    leaseExpirationDurationInSeconds: 120
    prefer-ip-address: true

management:
  endpoints:
    web:
      exposure:
        include: '*'

logging:
  level:
    com.hkd: DEBUG

message: Hello HKD from the GitHub